import 'dotenv/config'
import express from 'express'
import cors from 'cors'
import helmet from 'helmet'
import bcrypt from 'bcryptjs'
import jwt from 'jsonwebtoken'
import { differenceInCalendarDays, format } from 'date-fns'
import { z } from 'zod'
import { client, db, id, initializeDatabase, now, oid } from './db.js'
import { seed } from './seed.js'
import { allocateFefo } from './stock.js'

const app=express(),port=Number(process.env.API_PORT||4000),jwtSecret=process.env.JWT_SECRET||'development-only-secret-change-me'
app.use(helmet());app.use(cors({origin:process.env.CLIENT_ORIGIN||'*'}));app.use(express.json({limit:'100kb'}))

const today=()=>format(now(),'yyyy-MM-dd')
function auth(req:any,res:any,next:any){try{req.user=jwt.verify(req.headers.authorization?.replace(/^Bearer\s+/i,''),jwtSecret);next()}catch{res.status(401).json({message:'Please sign in again.'})}}
function roles(...allowed:string[]){return(req:any,res:any,next:any)=>allowed.includes(req.user.role)?next():res.status(403).json({message:'You do not have permission for this action.'})}
function publicDoc(value:any){if(!value)return null;const copy={...value,id:id(value)};delete copy._id;delete copy.passwordHash;return copy}

async function medicineRows(){const database=db(),medicines=await database.collection('medicines').find({active:true}).sort({nameEn:1}).toArray(),categories=await database.collection('categories').find().toArray(),batches=await database.collection('batches').find({medicineId:{$in:medicines.map(m=>m._id)}}).toArray(),suppliers=await database.collection('suppliers').find().toArray();return medicines.map(m=>{const own=batches.filter(b=>id(b.medicineId)===id(m)),usable=own.filter(b=>b.status==='available'&&new Date(b.expiryDate)>=new Date(`${today()}T00:00:00`)&&b.availableQuantity>0),available=usable.reduce((sum,b)=>sum+Number(b.availableQuantity),0),nearest=[...usable].sort((a,b)=>+new Date(a.expiryDate)-+new Date(b.expiryDate))[0]?.expiryDate,category=categories.find(c=>id(c)===id(m.categoryId));return{...publicDoc(m),Category:publicDoc(category),batches:own.map(b=>({...publicDoc(b),Supplier:publicDoc(suppliers.find(s=>id(s)===id(b.supplierId)))})),available,nearestExpiry:nearest||null,lowStock:available<=Number(m.reorderThreshold)}})}
async function alertRows(){const database=db(),alerts=await database.collection('alerts').find().sort({createdAt:-1}).toArray(),medicines=await database.collection('medicines').find().toArray(),batches=await database.collection('batches').find().toArray();return alerts.map(a=>({...publicDoc(a),Medicine:publicDoc(medicines.find(m=>id(m)===id(a.medicineId))),Batch:publicDoc(batches.find(b=>id(b)===id(a.batchId)))}))}
async function movementRows(limit=250){const database=db(),movements=await database.collection('stockMovements').find().sort({createdAt:-1}).limit(limit).toArray(),batches=await database.collection('batches').find({_id:{$in:movements.map(m=>m.batchId)}}).toArray(),medicines=await database.collection('medicines').find().toArray(),users=await database.collection('users').find().toArray();return movements.map(m=>{const batch=batches.find(b=>id(b)===id(m.batchId)),medicine=medicines.find(x=>id(x)===id(batch?.medicineId)),user=users.find(u=>id(u)===id(m.performedBy));return{...publicDoc(m),Batch:batch?{...publicDoc(batch),Medicine:publicDoc(medicine)}:null,User:publicDoc(user)}})}

async function ensureAlerts(){const database=db(),rows=await medicineRows();for(const med of rows){if(med.lowStock){if(!await database.collection('alerts').findOne({medicineId:oid(med.id),type:'low_stock',status:{$ne:'resolved'}}))await database.collection('alerts').insertOne({medicineId:oid(med.id),type:'low_stock',message:`${med.nameEn} is at ${med.available} ${med.baseUnit}; reorder level is ${med.reorderThreshold}.`,status:'unread',emailStatus:'pending',createdAt:now(),updatedAt:now()})}else await database.collection('alerts').updateMany({medicineId:oid(med.id),type:'low_stock',status:{$ne:'resolved'}},{$set:{status:'resolved',updatedAt:now()}});for(const batch of med.batches){if(Number(batch.availableQuantity)<=0)continue;const days=differenceInCalendarDays(new Date(batch.expiryDate),now()),checkpoint=days<0?0:days<=7?7:days<=30?30:days<=90?90:null;if(days<0&&batch.status!=='expired')await database.collection('batches').updateOne({_id:oid(batch.id)},{$set:{status:'expired',updatedAt:now()}});if(checkpoint!==null){const type=checkpoint===0?'expired':'expiring';if(!await database.collection('alerts').findOne({batchId:oid(batch.id),type,checkpoint}))await database.collection('alerts').insertOne({medicineId:oid(med.id),batchId:oid(batch.id),type,checkpoint,message:checkpoint===0?`${med.nameEn} batch ${batch.batchNumber} has expired.`:`${med.nameEn} batch ${batch.batchNumber} expires in ${days} day${days===1?'':'s'}.`,status:'unread',emailStatus:'pending',createdAt:now(),updatedAt:now()})}}}void sendPendingAlertEmails()}
async function sendPendingAlertEmails(){const key=process.env.RESEND_API_KEY,from=process.env.ALERT_FROM_EMAIL,recipients=(process.env.ALERT_RECIPIENTS||'').split(',').map(x=>x.trim()).filter(Boolean);if(!key||!from||!recipients.length)return;const collection=db().collection('alerts'),pending=await collection.find({emailStatus:'pending',status:{$ne:'resolved'}}).limit(20).toArray();for(const alert of pending){try{const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json','Idempotency-Key':`inventory-alert-${id(alert)}`},body:JSON.stringify({from,to:recipients,reply_to:process.env.ALERT_REPLY_TO||undefined,subject:`Suwasetha inventory: ${alert.type.replace('_',' ')}`,text:`${alert.message}\n\nOpen ${process.env.APP_BASE_URL||'the inventory system'} to review this alert.`})});if(!response.ok)throw new Error(await response.text());await collection.updateOne({_id:alert._id},{$set:{emailStatus:'sent',updatedAt:now()}})}catch(error:any){await collection.updateOne({_id:alert._id},{$set:{emailStatus:'failed',updatedAt:now()}});console.error('Alert email failed:',error.message)}}}

app.get('/api/health',(_req,res)=>res.json({ok:true,database:'mongodb'}))
app.post('/api/auth/login',async(req,res,next)=>{try{const body=z.object({email:z.string().email(),password:z.string().min(1)}).parse(req.body),user=await db().collection('users').findOne({email:body.email.toLowerCase()});if(!user||!user.active||!await bcrypt.compare(body.password,user.passwordHash))return res.status(401).json({message:'Invalid email or password.'});const safe={id:id(user),role:user.role,email:user.email,name:user.name,preferredLanguage:user.preferredLanguage,mustChangePassword:user.mustChangePassword};res.json({token:jwt.sign(safe,jwtSecret,{expiresIn:'8h'}),user:safe})}catch(e){next(e)}})
app.get('/api/me',auth,(req:any,res)=>res.json(req.user))
app.get('/api/medicines',auth,async(_req,res,next)=>{try{res.json(await medicineRows())}catch(e){next(e)}})
app.get('/api/categories',auth,async(_req,res,next)=>{try{res.json((await db().collection('categories').find({active:true}).sort({nameEn:1}).toArray()).map(publicDoc))}catch(e){next(e)}})
const medicineInput=z.object({code:z.string().trim().min(2).max(30).transform(value=>value.toUpperCase()),nameEn:z.string().trim().min(2).max(150),nameSi:z.string().trim().min(1).max(150),categoryId:z.string().min(1),baseUnit:z.enum(['kg','g','L','mL','tablet','capsule','pill','bottle','packet','jar','tube']),reorderThreshold:z.coerce.number().nonnegative(),active:z.boolean().optional()})
app.post('/api/medicines',auth,roles('administrator','storekeeper'),async(req:any,res,next)=>{try{const body=medicineInput.parse(req.body),category=await db().collection('categories').findOne({_id:oid(body.categoryId)});if(!category)return res.status(400).json({message:'Category not found.'});const document={...body,categoryId:category._id,active:body.active??true,createdAt:now(),updatedAt:now()},result=await db().collection('medicines').insertOne(document);await db().collection('auditEvents').insertOne({actorId:oid(req.user.id),action:'medicine.created',entityType:'medicine',entityId:id(result.insertedId),details:{code:document.code},createdAt:now()});res.status(201).json({...publicDoc({...document,_id:result.insertedId}),Category:publicDoc(category),batches:[],available:0,nearestExpiry:null,lowStock:true})}catch(e){next(e)}})
app.patch('/api/medicines/:id',auth,roles('administrator','storekeeper'),async(req:any,res,next)=>{try{const body=medicineInput.parse(req.body),category=await db().collection('categories').findOne({_id:oid(body.categoryId)});if(!category)return res.status(400).json({message:'Category not found.'});const changes={...body,categoryId:category._id,active:body.active??true,updatedAt:now()},result=await db().collection('medicines').findOneAndUpdate({_id:oid(req.params.id)},{$set:changes},{returnDocument:'after'});if(!result)return res.status(404).json({message:'Medicine not found.'});await db().collection('auditEvents').insertOne({actorId:oid(req.user.id),action:'medicine.updated',entityType:'medicine',entityId:id(result),details:{code:changes.code},createdAt:now()});res.json({...publicDoc(result),Category:publicDoc(category)})}catch(e){next(e)}})
app.get('/api/dashboard',auth,async(_req,res,next)=>{try{await ensureAlerts();const medicines=await medicineRows(),alerts=(await alertRows()).filter(a=>a.status!=='resolved').slice(0,8),movements=await movementRows(8),issued=await db().collection('dispenseEntries').aggregate([{$match:{businessDate:today()}},{$group:{_id:null,total:{$sum:'$requestedQuantity'}}}]).toArray();res.json({stats:{medicines:medicines.length,lowStock:medicines.filter(m=>m.lowStock).length,expiring:medicines.filter(m=>m.nearestExpiry&&differenceInCalendarDays(new Date(m.nearestExpiry),now())<=90).length,issuedToday:issued[0]?.total||0},medicines,alerts,movements})}catch(e){next(e)}})

app.post('/api/issues',auth,roles('administrator','dispenser'),async(req:any,res,next)=>{const session=client.startSession();try{const body=z.object({medicineId:z.string().min(1),quantity:z.coerce.number().positive(),note:z.string().max(500).optional()}).parse(req.body);let created:any;await session.withTransaction(async()=>{const database=db(),medicine=await database.collection('medicines').findOne({_id:oid(body.medicineId)},{session});if(!medicine)throw new Error('Medicine not found.');const batches=await database.collection('batches').find({medicineId:medicine._id,status:'available',availableQuantity:{$gt:0},expiryDate:{$gte:new Date(`${today()}T00:00:00`)}},{session}).sort({expiryDate:1,_id:1}).toArray(),allocations=allocateFefo(batches.map(b=>({id:id(b) as any,available:b.availableQuantity,expiryDate:format(b.expiryDate,'yyyy-MM-dd'),status:b.status})) as any,body.quantity,today()),entry={medicineId:medicine._id,staffId:oid(req.user.id),requestedQuantity:body.quantity,businessDate:today(),note:body.note,createdAt:now()};const entryResult=await database.collection('dispenseEntries').insertOne(entry,{session});created={...entry,id:id(entryResult.insertedId)};for(const allocation of allocations){const batch=batches.find(b=>id(b)===String(allocation.batchId))!,result=await database.collection('batches').updateOne({_id:batch._id,availableQuantity:{$gte:allocation.quantity}},{$inc:{availableQuantity:-allocation.quantity},$set:{updatedAt:now()}},{session});if(result.modifiedCount!==1)throw new Error('Stock changed while issuing. Please retry.');await database.collection('stockMovements').insertOne({batchId:batch._id,performedBy:oid(req.user.id),dispenseEntryId:entryResult.insertedId,type:'issue',quantityDelta:-allocation.quantity,note:body.note,createdAt:now()},{session})}});await ensureAlerts();res.status(201).json(created)}catch(e){next(e)}finally{await session.endSession()}})
app.post('/api/receipts',auth,roles('administrator','storekeeper'),async(req:any,res,next)=>{const session=client.startSession();try{const body=z.object({medicineId:z.string().min(1),supplierId:z.string().optional(),batchNumber:z.string().min(2).max(80),packCount:z.coerce.number().positive(),packSize:z.coerce.number().positive(),receivedDate:z.string(),expiryDate:z.string()}).parse(req.body);if(body.expiryDate<=body.receivedDate)return res.status(400).json({message:'Expiry date must be after the received date.'});const quantity=body.packCount*body.packSize;let batch:any;await session.withTransaction(async()=>{const database=db(),document={medicineId:oid(body.medicineId),supplierId:body.supplierId?oid(body.supplierId):undefined,batchNumber:body.batchNumber,receivedQuantity:quantity,availableQuantity:quantity,receivedDate:new Date(body.receivedDate),expiryDate:new Date(body.expiryDate),status:'available',createdAt:now(),updatedAt:now()},result=await database.collection('batches').insertOne(document,{session});batch={...document,id:id(result.insertedId)};await database.collection('stockMovements').insertOne({batchId:result.insertedId,performedBy:oid(req.user.id),type:'receipt',quantityDelta:quantity,note:`${body.packCount} packs × ${body.packSize}`,createdAt:now()},{session});await database.collection('auditEvents').insertOne({actorId:oid(req.user.id),action:'stock.received',entityType:'batch',entityId:id(result.insertedId),details:{quantity},createdAt:now()},{session})});await ensureAlerts();res.status(201).json(batch)}catch(e){next(e)}finally{await session.endSession()}})

app.get('/api/suppliers',auth,async(_req,res,next)=>{try{res.json((await db().collection('suppliers').find({active:true}).sort({name:1}).toArray()).map(publicDoc))}catch(e){next(e)}})
app.get('/api/movements',auth,async(_req,res,next)=>{try{res.json(await movementRows())}catch(e){next(e)}})
app.get('/api/alerts',auth,async(_req,res,next)=>{try{await ensureAlerts();res.json(await alertRows())}catch(e){next(e)}})
app.patch('/api/alerts/:id/acknowledge',auth,roles('administrator','storekeeper'),async(req:any,res,next)=>{try{await db().collection('alerts').updateOne({_id:oid(req.params.id)},{$set:{status:'acknowledged',acknowledgedAt:now(),updatedAt:now()}});res.json({ok:true})}catch(e){next(e)}})
app.get('/api/users',auth,roles('administrator'),async(_req,res,next)=>{try{res.json((await db().collection('users').find().project({passwordHash:0}).sort({name:1}).toArray()).map(publicDoc))}catch(e){next(e)}})
app.post('/api/users',auth,roles('administrator'),async(req:any,res,next)=>{try{const body=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(12),role:z.enum(['administrator','storekeeper','dispenser','auditor'])}).parse(req.body),document={name:body.name,email:body.email.toLowerCase(),passwordHash:await bcrypt.hash(body.password,12),role:body.role,preferredLanguage:'en',mustChangePassword:true,active:true,createdAt:now(),updatedAt:now()},result=await db().collection('users').insertOne(document);await db().collection('auditEvents').insertOne({actorId:oid(req.user.id),action:'user.created',entityType:'profile',entityId:id(result.insertedId),details:{email:body.email,role:body.role},createdAt:now()});res.status(201).json(publicDoc({...document,_id:result.insertedId}))}catch(e){next(e)}})
app.get('/api/audit',auth,roles('administrator','auditor'),async(_req,res,next)=>{
  try {
    const events=await db().collection('auditEvents').find().sort({createdAt:-1}).limit(250).toArray()
    const users=await db().collection('users').find().toArray()
    res.json(events.map(event=>({
      ...publicDoc(event),
      User:publicDoc(users.find(user=>id(user)===id(event.actorId))),
    })))
  } catch(error) {
    next(error)
  }
})
app.get('/api/reports/summary',auth,async(_req,res,next)=>{try{res.json({medicines:await medicineRows(),movements:await movementRows(1000)})}catch(e){next(e)}})
app.use((err:any,_req:any,res:any,_next:any)=>{console.error(err);if(err instanceof z.ZodError)return res.status(400).json({message:err.issues[0]?.message||'Invalid input.'});if(err?.code===11000)return res.status(409).json({message:'That email, code, or batch number already exists.'});res.status(400).json({message:err.message||'Something went wrong.'})})
export { app }

async function start(){await initializeDatabase();await seed();app.listen(port,()=>console.log(`API ready at http://localhost:${port} (MongoDB)`));setInterval(()=>void ensureAlerts(),6*60*60*1000)}
if(!process.env.VERCEL){start().catch(error=>{console.error('Failed to start API:',error);process.exit(1)})}


